### ISSUE TITLE
Refactoriser classes frontend suppression préfixe CS

### ISSUE THREAD

**Issue by jpm-cbna** [cbn-alpin/gn_module_conservation_strategy#18]
Il ne semble pas utile de préfixer le nom des classes du Frontend du module par "CS".
Il faudrait donc le retirer.

**Comment by ch-cbna** [comment]
Résolu avec le commit #[c535267](https://github.com/cbn-alpin/gn_module_conservation_strategy/pull/26/commits/c5352674e8b2648936abbad4950948f86dac5dd3)
