### ISSUE TITLE
[Form Bilan] Ajouter un champ pour la date de création

### ISSUE THREAD

**Issue by jpm-cbna** [cbn-alpin/gn_module_conservation_strategy#19]
Afin de pouvoir saisir les anciennes fiche bilan stationnel, il est nécessaire de pouvoir accéder au champ "Date de création" dans le formulaire d'édition d'une Fiche Bilan Stationnel.

**Comment by ch-cbna** [comment]
Réalisé dans le commit [https://github.com/cbn-alpin/gn_module_conservation_strategy/commit/b3d76382d41eb788bb70d745f7857f354e028776](url)
