### ISSUE TITLE
Fiches bilan stationnel : harmoniser accord/orthographe

### ISSUE THREAD

**Issue by noemiefort** [cbn-alpin/gn_module_conservation_strategy#24]
champ menace
commence le texte par une majuscule

champ action
mes propositions
niveau géographique territorial et pas territoriale
état d'avancement : mis en place et pas mise en place
mis en place -> mise en place de l'action ou date de mise en place
description de l'action : commencer le texte par une majuscule

**Comment by ch-cbna** [comment]
Au niveau du champ Action, les nomenclatures seront modifiées dans la BDD dès la prochaine mise à jour du GeoNature de Flore Sentinelle :
- niveau géographique territorial et pas territoriale
- état d'avancement : mis en place et pas mise en place

Lorsqu'une action est mise en place (type d'avancement), sa date correspond à la date de fin de réalisation de l'action (voir [wiki](https://wiki-intranet.cbn-alpin.fr/projets/scalp/appli-aide-decision/cahier-des-charges?s[]=implementation&s[]=date#t_action).
