### ISSUE TITLE
[Accueil] Contenu page d'accueil du module

### ISSUE THREAD

**Issue by jpm-cbna** [cbn-alpin/gn_module_conservation_strategy#8]
Le contenu suivant peut venir remplacer le contenu par défaut de la page d'accueil :

> Cette base « Actions de conservation » constitue un outil de gestion et de planification des actions de
> conservation de la flore sur le territoire du CBNA.
> Elle a été développée principalement dans le cadre de la stratégie de conservation de la flore alpine
> (SCALP), mais a pour vocation de regrouper des informations concernant tous les taxons prioritaires
> en région AuRA, PACA et sur le domaine alpin.
> Pour les taxons les mieux connus ou après une première phase d’acquisition de connaissances
> appelée ‘bilan stationnel’ (données saisies dans la base …..), les actions de conservation les plus
> pertinentes sont identifiées (notamment grâce à un arbre décisionnel), planifiées et les partenaires
> potentiels identifiés. Ces données concernant les actions sont calculées et basculées
> automatiquement dans la base « Actions de conservation ».
> Vous trouverez ici les actions concernant les taxons prioritaires sur votre territoire et pourrez
> également compléter les bilans stationnels réalisés. Lorsque les actions identifiées ont été réalisées,
> merci de mettre à jour la fiche action correspondante !
> Bonne consultation.

**Comment by jpm-cbna** [comment]
Si vous avez des idées de présentation et/ou d'amélioration du texte, vous pouvez les proposer en commentaire.
N'hésitez pas à fournir des exemples de présentation.

**Comment by LeaCBNA** [comment]
Prévoir de mettre un lien vers la page SCALP du site CBNA  et d'insérer les logos qui vont bien des financeurs SCALP ?

**Comment by vb-cbna** [comment]
Oui pour les logos SCALP ; prévoir aussi de pouvoir ajouter (par la suite ? ou dès maintenant ?) les logos des départements et des régions qui financement aussi les BS

**Comment by jpm-cbna** [comment]
> Oui pour les logos SCALP ; prévoir aussi de pouvoir ajouter (par la suite ? ou dès maintenant ?) les logos des départements et des régions qui financement aussi les BS

Il faudrait me fournir en les attachant à un commentaire de ce ticket les logos en question.

**Comment by jpm-cbna** [comment]
La page d'accueil a été réalisée. Elle est stockée dans le dépôt [floresentinelle-srv](https://github.com/cbn-alpin/floresentinelle-srv/tree/main/home/geonat/www/modules/cs/frontend/assets/templates).
